nome = str(input("Digite seu nome completo: ")).strip()
print("Analisando seu nome")
print("Seu nome maúsculas é {}".format(nome.upper()))
print("Seu nome minusculas é {}".format(nome.lower()))
print("Seu nome ao todo tem {} letras".format(len(nome)-nome.count(" ")))
print("Seu primeiro nome tem {} letras".format(nome.find(" ")))
