nome = str(input("Digite seu nome completo: ")).strip()
nome1 = nome.split()
print(f"Oi prazer em te conhecer: {nome}")
print("Seu primeiro nome é: {}".format(nome1[0]))
print("Seu ultimo nome é: {}".format(nome1[len(nome1)-1]))
